#
# MIT License
#
# (C) Copyright 2021-2022, 2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v2
name: cray-cfs-operator
version: 0.0.0-chart
description: Kubernetes resources for cfs-operator
keywords:
- cfs
- cray-cfs-operator
home: https://github.com/Cray-HPE/cfs-operator
sources:
- https://github.com/Cray-HPE/cfs-operator
- https://github.com/Cray-HPE/ansible-execution-environment
dependencies:
- name: cray-service
  version: ^7.0.0
  repository: https://artifactory.algol60.net/artifactory/csm-helm-charts/
maintainers:
- name: rbak-hpe
  email: ryan.bak@hpe.com
- name: rkleinman-hpe
  email: randy.kleinman@hpe.com
appVersion: 0.0.0-image
annotations:
  artifacthub.io/images: |
    - name: cray-cfs-operator
      image: artifactory.algol60.net/csm-docker/S-T-A-B-L-E/cray-cfs-operator:0.0.0-image
    - name: cray-aee
      image: artifactory.algol60.net/csm-docker/stable/cray-aee:0.0.0-aee
  artifacthub.io/license: MIT
