# Please refer to https://github.com/Cray-HPE/base-charts/tree/master/kubernetes/cray-service/values.yaml
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

util_image:
  repository: alpine/git
  version: 1.0.15
ims_image:
  repository: cray/cray-cfs-operator
aee_image:
  repository: cray/cray-aee
  version: IMAGE_CRAY_AEE_TAG

service_name: cray-cfs-operator
cray-service:
  type: Deployment
  nameOverride: cray-cfs-operator
  fullNameOverride: cray-cfs-operator
  serviceAccountName: cray-cfs
  labels:
    app: cray-cfs-operator
  containers:
    cray-cfs-operator:
      name: cray-cfs-operator
      image:
        repository: cray/cray-cfs-operator
      env:
      - name: CFS_OPERATOR_LOG_LEVEL
        value: "INFO"
      - name: CRAY_CFS_NAMESPACE
        value: "services"
      - name: CRAY_CFS_UTIL_IMAGE
        valueFrom:
          configMapKeyRef:
            name: cray-cfs-operator-config
            key: cray_cfs_util_image
      - name: CRAY_CFS_AEE_IMAGE
        valueFrom:
          configMapKeyRef:
            name: cray-cfs-operator-config
            key: cray_cfs_aee_image
      - name: CRAY_CFS_CONFIGMAP_PUBLIC_KEY
        value: "cray-configmap-ca-public-key"
      - name: CRAY_CFS_CA_PUBLIC_KEY
        value: "certificate_authority.crt"
      - name: CRAY_CFS_TRUST_CERT_SECRET
        value: "cfstrustcertificate"
      - name: CRAY_CFS_TRUST_KEY_SECRET
        value: "cfstrust"
      - name: CRAY_CFS_IMS_IMAGE
        valueFrom:
          configMapKeyRef:
            name: cray-cfs-operator-config
            key: cray_cfs_ims_image
      - name: CRAY_CFS_SERVICE_ACCOUNT
        value: "cray-cfs"
      - name : VCS_USER_CREDENTIALS
        value: "vcs-user-credentials"
      resources:
        requests:
          memory: "150Mi"
          cpu: "200m"
        limits:
          memory: "250Mi"
          cpu: "500m"
      livenessProbe:
        exec:
          command:
          - python3
          - "-m"
          - "cray.cfs.operator.liveness"
        initialDelaySeconds: 10
        periodSeconds: 30
        timeoutSeconds: 3
  service:
    enabled: false
