apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cray-cfs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cray-cfs
subjects:
- kind: ServiceAccount
  name: cray-cfs
  namespace: services