---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cray-cfs
  namespace: services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cray-cfs
subjects:
  - kind: ServiceAccount
    name: cray-cfs
    namespace: services
---
# cray-cfs-operator pod needs to run as root
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cray-cfs-psp
  namespace: services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
  - kind: ServiceAccount
    name: cray-cfs
    namespace: services
