apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cray-cfs
  namespace: services
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["cms.cray.com"]
  resources: ["cfsessions"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get"]
- apiGroups: ["networking.istio.io"]
  resources: ["destinationrules"]
  verbs: ["create", "delete", "get"]
